### ISSUE TITLE
Redundant lines in HCIRN code?

### ISSUE THREAD

**Issue by vishwa91** [MaPePeR/jsColorblindSimulator#1]
Firstly, thanks a ton for hosting this code online. I have been searching for programmatic ways to generate colorblind images and this was the only useful code I found online!

I was parsing the javascript file, `hcirn_colorblind_simulator.js` and found the following few lines:

```javascript
if (cu &lt; rBlind[t].cpu) {
        clm = (rBlind[t].cpv - cv) / (rBlind[t].cpu - cu);    
} else {
        clm = (cv - rBlind[t].cpv) / (cu - rBlind[t].cpu); 
}
```

If I understand right, the two if-else expressions evaluate to the same value. Is this a code bug, or just redundant lines?

Regards.

**Comment by MaPePeR** [comment]
I haven't written that code myself, so I can only guess.

At first glance it looks like the result is the same. Depending on the data types this might make sense, though: if `cu` and `.cpu` are unsigned this might be necessary to prevent an underflow?

So maybe this was ported from C to JavaScript?

If it's floats there might be some numerical reasons for this?

I can only speculate myself, so you might be correct, that it's just redundant or a bug.

**Comment by vishwa91** [comment]
I agree that the reasons could just be for numerical purposes. Thanks for the quick response! I'll close this issue for now.
